[package]
name = "open-knight"
version = "0.1.0"
description = "An open source chess db and analysis app"
authors = ["Reid Pritchard"]
edition = "2021"

[lib]
name = "open_knight_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shakmaty = "0.27.2"
chumsky = "0.9.0"
ts-bind = "0.1.7"
tauri-plugin-sql = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2", features = [
    "sqlite",
] }
tokio = { version = "1.0", features = ["full"] }
