// This file was automatically generated by ts_bind, do not modify it manually
import type { ValidMove } from "./ValidMove";

export interface AllValidMoves {
   position: string;
   moves: (ValidMove)[];
}