// This file was automatically generated by ts_bind, do not modify it manually
import type { Game } from "./Game";
import type { APIMove } from "./APIMove";

export interface APIGame {
   game_data: Game;
   moves: (APIMove)[];
}