// This file was automatically generated by ts_bind, do not modify it manually
import type { Header } from "./Header";
import type { Game } from "./Game";
import type { APIMove } from "./APIMove";

export interface APIGame {
   game: Game;
   moves: (APIMove)[];
   headers: (Header)[];
}