// This file was automatically generated by ts_bind, do not modify it manually
import type { Tournament } from "./Tournament";
import type { Player } from "./Player";
import type { Opening } from "./Opening";
import type { Game } from "./Game";
import type { APIMove } from "./APIMove";

export interface APIGame {
   game: Game;
   moves: (APIMove)[];
   white_player: Player | null;
   black_player: Player | null;
   tournament: Tournament | null;
   opening: Opening | null;
}