// This file was automatically generated by ts_bind, do not modify it manually
import type { Position } from "./Position";
import type { Move } from "./Move";
import type { Evaluation } from "./Evaluation";
import type { Annotation } from "./Annotation";

export interface APIMove {
   game_move: Move;
   position: Position;
   annotations: (Annotation)[];
   evaluation: Evaluation | null;
}