// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user of the application. Wraps the user db entity.
 */
export type AppUser = { user_id: number | null, username: string, email: string, created_at: string | null, };
