// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChessTournament = { id: number, name: string, tournament_type: string | null, time_control: string | null, start_date: string | null, end_date: string | null, location: string | null, };
