// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessTreeNode } from "./ChessTreeNode";

export type ChessMoveTree = { game_id: number, nodes: { value: ChessTreeNode | null, version: number }[], root_id?: { idx: number, version: number }, current_node_id?: { idx: number, version: number }, };
