// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessMove } from "./ChessMove";
import type { ChessPosition } from "./ChessPosition";

export type ChessTreeNode = { position: ChessPosition, game_move: ChessMove | null, parent_id: { idx: number, version: number } | null, children_ids: { idx: number, version: number }[], };
