// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChessPlayer = { id: number, name: string, elo: number | null, country: string | null, };
