// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessAnnotation } from "./ChessAnnotation";
import type { ChessMoveTime } from "./ChessMoveTime";
import type { ChessPosition } from "./ChessPosition";

export type ChessMove = { id: number, game_id: number, ply_number: number, san: string, uci: string, position: ChessPosition | null, annotations: Array<ChessAnnotation>, time_info: ChessMoveTime | null, parent_move_id: number | null, };
