// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChessEvaluation = { score: number | null, eval_type: string | null, depth: number | null, engine: string | null, };
