// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessEvaluation } from "./ChessEvaluation";

export type ChessPosition = {
	id: number;
	fen: string;
	evaluations: Array<ChessEvaluation>;
	variant: string | null;
};
