// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessAnnotation } from "./ChessAnnotation";
import type { ChessMoveTime } from "./ChessMoveTime";
import type { ChessPosition } from "./ChessPosition";

export type ChessMove = { id: number, game_id: number, move_number: number | null, player_color: string | null, notation: string, position: ChessPosition | null, annotations: Array<ChessAnnotation>, time_info: ChessMoveTime | null, variations: Array<ChessMove>, next_move: ChessMove | null, };
