// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChessEvaluation = { score: number | null, eval_type: string | null, is_mate: boolean, depth: number | null, engine: string | null, principal_variation: Array<string>, };
