// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChessOpening = {
	id: number;
	eco: string | null;
	name: string | null;
	variation: string | null;
};
