// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessMove } from "./ChessMove";
import type { ChessOpening } from "./ChessOpening";
import type { ChessPlayer } from "./ChessPlayer";
import type { ChessTournament } from "./ChessTournament";

export type ChessGame = { id: number, white_player: ChessPlayer, black_player: ChessPlayer, tournament: ChessTournament | null, opening: ChessOpening | null, result: string, round: number | null, date: string, moves: Array<ChessMove>, tags: Array<string>, fen: string | null, pgn: string | null, };
