// This file was automatically generated by ts_bind, do not modify it manually
import type { Tournament } from "./Tournament";
import type { Player } from "./Player";
import type { Opening } from "./Opening";
import type { Game } from "./Game";

export interface ExplorerGame {
   game: Game;
   white_player: Player | null;
   black_player: Player | null;
   tournament: Tournament | null;
   opening: Opening | null;
}