// This file was automatically generated by ts_bind, do not modify it manually
import type { HeaderTuple } from "./HeaderTuple";

export interface ExplorerGame {
   id: number;
   headers: (HeaderTuple)[];
}