// This file was automatically generated by ts_bind, do not modify it manually
import type { Header } from "./Header";
import type { Game } from "./Game";

export interface ExplorerGame {
   game: Game;
   headers: (Header)[];
}