// This file was automatically generated by ts_bind, do not modify it manually
import type { Tournament } from "./Tournament";
import type { Tag } from "./Tag";
import type { Position } from "./Position";
import type { Player } from "./Player";
import type { Opening } from "./Opening";
import type { Move } from "./Move";
import type { Game } from "./Game";
import type { Annotation } from "./Annotation";

export interface FullGame {
   game: Game;
   moves: (Move)[];
   positions: (Position)[];
   annotations: (Annotation)[];
   white_player: Player | null;
   black_player: Player | null;
   tournament: Tournament | null;
   opening: Opening | null;
   tags: (Tag)[];
}