// This file was automatically generated by ts_bind, do not modify it manually
import type { Move } from "./Move";
import type { Header } from "./Header";
import type { Game } from "./Game";

export interface FullGame {
   game: Game;
   moves: (Move)[];
   headers: (Header)[];
}