// This file was automatically generated by ts_bind, do not modify it manually

export interface Game {
   id: number | null;
   pgn: string;
   player_white: string | null;
   player_black: string | null;
   event: string | null;
   date_text: string | null;
   result: string | null;
   annotations: string | null;
   opening_name: string | null;
}