// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryParams = { limit: bigint | null, offset: bigint | null, fields: Array<string> | null, filter: { [key in string]?: string } | null, load_moves: boolean | null, load_tags: boolean | null, };
