// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time management strategies for analysis
 *
 * For a single position analysis, total and fixed result in the same behavior.
 */
export type TimeStrategy = { "TotalBudget": { total_seconds: bigint, } } | { "FixedPerMove": { seconds_per_move: bigint, } } | { "FixedDepth": { depth: number, } };
