//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod annotation;
pub mod evaluation;
pub mod game;
pub mod game_header;
pub mod game_tag;
pub mod r#move;
pub mod move_tag;
pub mod move_time_tracking;
pub mod opening;
pub mod player;
pub mod position;
pub mod tag;
pub mod tournament;
pub mod user;
