//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "move_time_tracking")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub time_tracking_id: i32,
    pub move_id: i32,
    pub time_spent_ms: Option<i32>,
    pub time_left_ms: Option<i32>,
    pub clock_type: Option<String>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::r#move::Entity",
        from = "Column::MoveId",
        to = "super::r#move::Column::MoveId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Move,
}

impl Related<super::r#move::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Move.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
