//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "position")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub position_id: i32,
    #[sea_orm(unique)]
    pub fen: String,
    pub fen_hash: String,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::evaluation::Entity")]
    Evaluation,
    #[sea_orm(has_many = "super::r#move::Entity")]
    Move,
}

impl Related<super::evaluation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evaluation.def()
    }
}

impl Related<super::r#move::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Move.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
