//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::annotation::Entity as Annotation;
pub use super::evaluation::Entity as Evaluation;
pub use super::game::Entity as Game;
pub use super::game_tag::Entity as GameTag;
pub use super::move_tag::Entity as MoveTag;
pub use super::move_time_tracking::Entity as MoveTimeTracking;
pub use super::opening::Entity as Opening;
pub use super::player::Entity as Player;
pub use super::position::Entity as Position;
pub use super::r#move::Entity as Move;
pub use super::tag::Entity as Tag;
pub use super::tournament::Entity as Tournament;
pub use super::user::Entity as User;
